name: Java CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Compile Java Code
      run: javac -cp ".:lib/junit-4.13.2.jar" -d assignment/out/ assignment/src/**/*.java assignment/test/**/*.java

    - name: Run All JUnit Tests
      run: |
        for test in $(find out/ -name '*Test*.class'); do
          test_class=$(echo $test | sed 's/out\///' | sed 's/\//./g' | sed 's/.class$//')
          java -cp ".:lib/junit-4.13.2.jar:out/" org.junit.runner.JUnitCore $test_class
        done
